services:
  db:
    image: postgres:15
    container_name: prohome_b2c_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2008
      POSTGRES_DB: prohome_b2c_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: prohome_b2c_app
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:2008@db:5432/prohome_b2c_db?schema=public
    ports:
      - '4000:4000'
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - uploads_data:/app/core/uploads
    # 'command' so'zi 'volumes' bilan bir xil ustunda bo'lishi shart:
    command: >
      sh -c "export DATABASE_URL='postgresql://postgres:2008@db:5432/prohome_b2c_db?schema=public' && 
      npx prisma generate && 
      npx prisma db push --accept-data-loss && 
      node dist/main.js"

volumes:
  postgres_data:
  uploads_data: