export const UZBEKISTAN_REGIONS = [
  {
    nameUz: "Andijon viloyati",
    nameUzCyrl: "Андижон вилояти",
    nameRu: "Андижанская область",
    districts: [
      { nameUz: "Andijon tumani", nameUzCyrl: "Андижон тумани", nameRu: "Андижанский район" },
      { nameUz: "Asaka tumani", nameUzCyrl: "Асака тумани", nameRu: "Асакинский район" },
      { nameUz: "Baliqchi tumani", nameUzCyrl: "Балиқчи тумани", nameRu: "Балыкчинский район" },
      { nameUz: "Bo'ston tumani", nameUzCyrl: "Бўстон тумани", nameRu: "Бустанский район" },
      { nameUz: "Buloqboshi tumani", nameUzCyrl: "Булоқбоши тумани", nameRu: "Булакбашинский район" },
      { nameUz: "Izboskan tumani", nameUzCyrl: "Избоскан тумани", nameRu: "Избасканский район" },
      { nameUz: "Jalolquduq tumani", nameUzCyrl: "Жалолқудуқ тумани", nameRu: "Джалалкудукский район" },
      { nameUz: "Marhamat tumani", nameUzCyrl: "Марҳамат тумани", nameRu: "Мархаматский район" },
      { nameUz: "Oltinko'l tumani", nameUzCyrl: "Олтинкўл тумани", nameRu: "Алтынкульский район" },
      { nameUz: "Paxtaobod tumani", nameUzCyrl: "Пахтаобод тумани", nameRu: "Пахтаабадский район" },
      { nameUz: "Qo'rg'ontepa tumani", nameUzCyrl: "Қўрғонтепа тумани", nameRu: "Кургантепинский район" },
      { nameUz: "Shahrixon tumani", nameUzCyrl: "Шаҳрихон тумани", nameRu: "Шахриханский район" },
      { nameUz: "Ulug'nor tumani", nameUzCyrl: "Улуғнор тумани", nameRu: "Улугнорский район" },
      { nameUz: "Xo'jaobod tumani", nameUzCyrl: "Хўжаобод тумани", nameRu: "Ходжаабадский район" },
    ],
  },
  {
    nameUz: "Buxoro viloyati",
    nameUzCyrl: "Бухоро вилояти",
    nameRu: "Бухарская область",
    districts: [
      { nameUz: "Buxoro tumani", nameUzCyrl: "Бухоро тумани", nameRu: "Бухарский район" },
      { nameUz: "G'ijduvon tumani", nameUzCyrl: "Ғиждувон тумани", nameRu: "Гиждуванский район" },
      { nameUz: "Jondor tumani", nameUzCyrl: "Жондор тумани", nameRu: "Жандарский район" },
      { nameUz: "Kogon tumani", nameUzCyrl: "Когон тумани", nameRu: "Каганский район" },
      { nameUz: "Olot tumani", nameUzCyrl: "Олот тумани", nameRu: "Алатский район" },
      { nameUz: "Peshku tumani", nameUzCyrl: "Пешку тумани", nameRu: "Пешкунский район" },
      { nameUz: "Qorako'l tumani", nameUzCyrl: "Қоракўл тумани", nameRu: "Каракульский район" },
      { nameUz: "Qorovulbozor tumani", nameUzCyrl: "Қоровулбозор тумани", nameRu: "Каравулбазарский район" },
      { nameUz: "Romitan tumani", nameUzCyrl: "Ромитан тумани", nameRu: "Ромитанский район" },
      { nameUz: "Shofirkon tumani", nameUzCyrl: "Шофиркон тумани", nameRu: "Шафирканский район" },
      { nameUz: "Vobkent tumani", nameUzCyrl: "Вобкент тумани", nameRu: "Вабкентский район" },
    ],
  },
  {
    nameUz: "Farg'ona viloyati",
    nameUzCyrl: "Фарғона вилояти",
    nameRu: "Ферганская область",
    districts: [
      { nameUz: "Bag'dod tumani", nameUzCyrl: "Бағдод тумани", nameRu: "Багдадский район" },
      { nameUz: "Beshariq tumani", nameUzCyrl: "Бешариқ тумани", nameRu: "Бешарыкский район" },
      { nameUz: "Buvayda tumani", nameUzCyrl: "Бувайда тумани", nameRu: "Бувайдинский район" },
      { nameUz: "Dang'ara tumani", nameUzCyrl: "Данғара тумани", nameRu: "Дангаринский район" },
      { nameUz: "Farg'ona tumani", nameUzCyrl: "Фарғона тумани", nameRu: "Ферганский район" },
      { nameUz: "Furqat tumani", nameUzCyrl: "Фурқат тумани", nameRu: "Фуркатский район" },
      { nameUz: "Oltiariq tumani", nameUzCyrl: "Олтиариқ тумани", nameRu: "Алтыарыкский район" },
      { nameUz: "Qo'shtepa tumani", nameUzCyrl: "Қўштепа тумани", nameRu: "Куштепинский район" },
      { nameUz: "Quva tumani", nameUzCyrl: "Қува тумани", nameRu: "Кувинский район" },
      { nameUz: "Rishton tumani", nameUzCyrl: "Риштон тумани", nameRu: "Риштанский район" },
      { nameUz: "So'x tumani", nameUzCyrl: "Сўх тумани", nameRu: "Сохский район" },
      { nameUz: "Toshloq tumani", nameUzCyrl: "Тошлоқ тумани", nameRu: "Ташлакский район" },
      { nameUz: "Uchko'prik tumani", nameUzCyrl: "Учкўприк тумани", nameRu: "Учкуприкский район" },
      { nameUz: "Yozyovon tumani", nameUzCyrl: "Ёзёвон тумани", nameRu: "Язъяванский район" },
    ],
  },
  {
    nameUz: "Jizzax viloyati",
    nameUzCyrl: "Жиззах вилояти",
    nameRu: "Джизакская область",
    districts: [
      { nameUz: "Arnasoy tumani", nameUzCyrl: "Арнасой тумани", nameRu: "Арнасайский район" },
      { nameUz: "Baxmal tumani", nameUzCyrl: "Бахмал тумани", nameRu: "Бахмальский район" },
      { nameUz: "Do'stlik tumani", nameUzCyrl: "Дўстлик тумани", nameRu: "Дустликский район" },
      { nameUz: "Forish tumani", nameUzCyrl: "Фориш тумани", nameRu: "Фаришский район" },
      { nameUz: "G'allaorol tumani", nameUzCyrl: "Ғаллаорол тумани", nameRu: "Галляаральский район" },
      { nameUz: "Jizzax tumani", nameUzCyrl: "Жиззах тумани", nameRu: "Джизакский район" },
      { nameUz: "Mirzacho'l tumani", nameUzCyrl: "Мирзачўл тумани", nameRu: "Мирзачульский район" },
      { nameUz: "Paxtakor tumani", nameUzCyrl: "Пахтакор тумани", nameRu: "Пахтакорский район" },
      { nameUz: "Yangiobod tumani", nameUzCyrl: "Янгиобод тумани", nameRu: "Янгиабадский район" },
      { nameUz: "Zafarobod tumani", nameUzCyrl: "Зафаробод тумани", nameRu: "Зафарабадский район" },
      { nameUz: "Zarbdor tumani", nameUzCyrl: "Зарбдор тумани", nameRu: "Зарбдарский район" },
      { nameUz: "Zomin tumani", nameUzCyrl: "Зомин тумани", nameRu: "Заминский район" },
    ],
  },
  {
    nameUz: "Namangan viloyati",
    nameUzCyrl: "Наманган вилояти",
    nameRu: "Наманганская область",
    districts: [
      { nameUz: "Chortoq tumani", nameUzCyrl: "Чортоқ тумани", nameRu: "Чартакский район" },
      { nameUz: "Chust tumani", nameUzCyrl: "Чуст тумани", nameRu: "Чустский район" },
      { nameUz: "Kosonsoy tumani", nameUzCyrl: "Косонсой тумани", nameRu: "Касансайский район" },
      { nameUz: "Mingbuloq tumani", nameUzCyrl: "Мингбулоқ тумани", nameRu: "Мингбулакский район" },
      { nameUz: "Namangan tumani", nameUzCyrl: "Наманган тумани", nameRu: "Наманганский район" },
      { nameUz: "Norin tumani", nameUzCyrl: "Норин тумани", nameRu: "Нарынский район" },
      { nameUz: "Pop tumani", nameUzCyrl: "Поп тумани", nameRu: "Папский район" },
      { nameUz: "To'raqo'rg'on tumani", nameUzCyrl: "Тўрақўрғон тумани", nameRu: "Туракурганский район" },
      { nameUz: "Uchqo'rg'on tumani", nameUzCyrl: "Учқўрғон тумани", nameRu: "Учкурганский район" },
      { nameUz: "Uychi tumani", nameUzCyrl: "Уйчи тумани", nameRu: "Уйчинский район" },
      { nameUz: "Yangiqo'rg'on tumani", nameUzCyrl: "Янгиқўрғон тумани", nameRu: "Янгикурганский район" },
    ],
  },
  {
    nameUz: "Navoiy viloyati",
    nameUzCyrl: "Навоий вилояти",
    nameRu: "Навоийская область",
    districts: [
      { nameUz: "Karmana tumani", nameUzCyrl: "Кармана тумани", nameRu: "Карманинский район" },
      { nameUz: "Konimex tumani", nameUzCyrl: "Конимех тумани", nameRu: "Конимехский район" },
      { nameUz: "Navbahor tumani", nameUzCyrl: "Навбаҳор тумани", nameRu: "Навбахорский район" },
      { nameUz: "Nurota tumani", nameUzCyrl: "Нурота тумани", nameRu: "Нуратинский район" },
      { nameUz: "Qiziltepa tumani", nameUzCyrl: "Қизилтепа тумани", nameRu: "Кизилтепинский район" },
      { nameUz: "Tomdi tumani", nameUzCyrl: "Томди тумани", nameRu: "Томдинский район" },
      { nameUz: "Uchquduq tumani", nameUzCyrl: "Учқудуқ тумани", nameRu: "Учкудукский район" },
      { nameUz: "Xatirchi tumani", nameUzCyrl: "Хатирчи тумани", nameRu: "Хатырчинский район" },
    ],
  },
  {
    nameUz: "Qashqadaryo viloyati",
    nameUzCyrl: "Қашқадарё вилояти",
    nameRu: "Кашкадарьинская область",
    districts: [
      { nameUz: "Chiroqchi tumani", nameUzCyrl: "Чироқчи тумани", nameRu: "Чиракчинский район" },
      { nameUz: "Dehqonobod tumani", nameUzCyrl: "Деҳқонобод тумани", nameRu: "Дехканабадский район" },
      { nameUz: "G'uzor tumani", nameUzCyrl: "Ғузор тумани", nameRu: "Гузарский район" },
      { nameUz: "Kasbi tumani", nameUzCyrl: "Касби тумани", nameRu: "Касбинский район" },
      { nameUz: "Kitob tumani", nameUzCyrl: "Китоб тумани", nameRu: "Китабский район" },
      { nameUz: "Koson tumani", nameUzCyrl: "Косон тумани", nameRu: "Касанский район" },
      { nameUz: "Mirishkor tumani", nameUzCyrl: "Миришкор тумани", nameRu: "Миришкорский район" },
      { nameUz: "Muborak tumani", nameUzCyrl: "Муборак тумани", nameRu: "Мубарекский район" },
      { nameUz: "Nishon tumani", nameUzCyrl: "Нишон тумани", nameRu: "Нишанский район" },
      { nameUz: "Qamashi tumani", nameUzCyrl: "Қамаши тумани", nameRu: "Камашинский район" },
      { nameUz: "Qarshi tumani", nameUzCyrl: "Қарши тумани", nameRu: "Каршинский район" },
      { nameUz: "Shahrisabz tumani", nameUzCyrl: "Шаҳрисабз тумани", nameRu: "Шахрисабзский район" },
      { nameUz: "Yakkabog' tumani", nameUzCyrl: "Яккабоғ тумани", nameRu: "Яккабагский район" },
    ],
  },
  {
    nameUz: "Samarqand viloyati",
    nameUzCyrl: "Самарқанд вилояти",
    nameRu: "Самаркандская область",
    districts: [
      { nameUz: "Bulung'ur tumani", nameUzCyrl: "Булунғур тумани", nameRu: "Булунгурский район" },
      { nameUz: "Ishtixon tumani", nameUzCyrl: "Иштихон тумани", nameRu: "Иштыханский район" },
      { nameUz: "Jomboy tumani", nameUzCyrl: "Жомбой тумани", nameRu: "Джамбайский район" },
      { nameUz: "Kattaqo'rg'on tumani", nameUzCyrl: "Каттақўрғон тумани", nameRu: "Каттакурганский район" },
      { nameUz: "Narpay tumani", nameUzCyrl: "Нарпай тумани", nameRu: "Нарпайский район" },
      { nameUz: "Oqdaryo tumani", nameUzCyrl: "Оқдарё тумани", nameRu: "Акдарьинский район" },
      { nameUz: "Paxtachi tumani", nameUzCyrl: "Пахтачи тумани", nameRu: "Пахтачийский район" },
      { nameUz: "Pastdarg'om tumani", nameUzCyrl: "Пастдарғом тумани", nameRu: "Пастдаргомский район" },
      { nameUz: "Payariq tumani", nameUzCyrl: "Пайариқ тумани", nameRu: "Пайарыкский район" },
      { nameUz: "Samarqand tumani", nameUzCyrl: "Самарқанд тумани", nameRu: "Самаркандский район" },
      { nameUz: "Toyloq tumani", nameUzCyrl: "Тойлоқ тумани", nameRu: "Тайлакский район" },
      { nameUz: "Urgut tumani", nameUzCyrl: "Ургут тумани", nameRu: "Ургутский район" },
    ],
  },
  {
    nameUz: "Sirdaryo viloyati",
    nameUzCyrl: "Сирдарё вилояти",
    nameRu: "Сырдарьинская область",
    districts: [
      { nameUz: "Boyovut tumani", nameUzCyrl: "Боёвут тумани", nameRu: "Баяутский район" },
      { nameUz: "Guliston tumani", nameUzCyrl: "Гулистон тумани", nameRu: "Гулистанский район" },
      { nameUz: "Mirzaobod tumani", nameUzCyrl: "Мирзаобод тумани", nameRu: "Мирзаабадский район" },
      { nameUz: "Oqoltin tumani", nameUzCyrl: "Оқолтин тумани", nameRu: "Акалтынский район" },
      { nameUz: "Sardoba tumani", nameUzCyrl: "Сардоба тумани", nameRu: "Сардобинский район" },
      { nameUz: "Sayxunobod tumani", nameUzCyrl: "Сайхунобод тумани", nameRu: "Сайхунабадский район" },
      { nameUz: "Sirdaryo tumani", nameUzCyrl: "Сирдарё тумани", nameRu: "Сырдарьинский район" },
      { nameUz: "Xovos tumani", nameUzCyrl: "Ховос тумани", nameRu: "Хавастский район" },
    ],
  },
  {
    nameUz: "Surxondaryo viloyati",
    nameUzCyrl: "Сурхондарё вилояти",
    nameRu: "Сурхандарьинская область",
    districts: [
      { nameUz: "Angor tumani", nameUzCyrl: "Ангор тумани", nameRu: "Ангорский район" },
      { nameUz: "Bandixon tumani", nameUzCyrl: "Бандихон тумани", nameRu: "Бандиханский район" },
      { nameUz: "Boysun tumani", nameUzCyrl: "Бойсун тумани", nameRu: "Байсунский район" },
      { nameUz: "Denov tumani", nameUzCyrl: "Денов тумани", nameRu: "Денауский район" },
      { nameUz: "Jarqo'rg'on tumani", nameUzCyrl: "Жарқўрғон тумани", nameRu: "Джаркурганский район" },
      { nameUz: "Muzrabot tumani", nameUzCyrl: "Музработ тумани", nameRu: "Музрабатский район" },
      { nameUz: "Oltinsoy tumani", nameUzCyrl: "Олтинсой тумани", nameRu: "Алтынсайский район" },
      { nameUz: "Qiziriq tumani", nameUzCyrl: "Қизириқ тумани", nameRu: "Кизирикский район" },
      { nameUz: "Qumqo'rg'on tumani", nameUzCyrl: "Қумқўрғон тумани", nameRu: "Кумкурганский район" },
      { nameUz: "Sariosiyo tumani", nameUzCyrl: "Сариосиё тумани", nameRu: "Сариасийский район" },
      { nameUz: "Sherobod tumani", nameUzCyrl: "Шеробод тумани", nameRu: "Шерабадский район" },
      { nameUz: "Sho'rchi tumani", nameUzCyrl: "Шўрчи тумани", nameRu: "Шурчинский район" },
      { nameUz: "Termiz tumani", nameUzCyrl: "Термиз тумани", nameRu: "Термезский район" },
      { nameUz: "Uzun tumani", nameUzCyrl: "Узун тумани", nameRu: "Узунский район" },
    ],
  },
  {
    nameUz: "Toshkent viloyati",
    nameUzCyrl: "Тошкент вилояти",
    nameRu: "Ташкентская область",
    districts: [
      { nameUz: "Bekobod tumani", nameUzCyrl: "Бекобод тумани", nameRu: "Бекабадский район" },
      { nameUz: "Bo'ka tumani", nameUzCyrl: "Бўка тумани", nameRu: "Букинский район" },
      { nameUz: "Bo'stonliq tumani", nameUzCyrl: "Бўстонлиқ тумани", nameRu: "Бостанлыкский район" },
      { nameUz: "Chinoz tumani", nameUzCyrl: "Чиноз тумани", nameRu: "Чиназский район" },
      { nameUz: "Ohangaron tumani", nameUzCyrl: "Оҳангарон тумани", nameRu: "Ахангаранский район" },
      { nameUz: "Oqqo'rg'on tumani", nameUzCyrl: "Оққўрғон тумани", nameRu: "Аккурганский район" },
      { nameUz: "Parkent tumani", nameUzCyrl: "Паркент тумани", nameRu: "Паркентский район" },
      { nameUz: "Piskent tumani", nameUzCyrl: "Пискент тумани", nameRu: "Пскентский район" },
      { nameUz: "Quyi Chirchiq tumani", nameUzCyrl: "Қуйи Чирчиқ тумани", nameRu: "Нижнечирчикский район" },
      { nameUz: "Toshkent tumani", nameUzCyrl: "Тошкент тумани", nameRu: "Ташкентский район" },
      { nameUz: "Yangiyo'l tumani", nameUzCyrl: "Янгийўл тумани", nameRu: "Янгиюльский район" },
      { nameUz: "Yuqori Chirchiq tumani", nameUzCyrl: "Юқори Чирчиқ тумани", nameRu: "Верхнечирчикский район" },
      { nameUz: "Zangiota tumani", nameUzCyrl: "Зангиота тумани", nameRu: "Зангиатинский район" },
    ],
  },
  {
    nameUz: "Xorazm viloyati",
    nameUzCyrl: "Хоразм вилояти",
    nameRu: "Хорезмская область",
    districts: [
      { nameUz: "Bog'ot tumani", nameUzCyrl: "Боғот тумани", nameRu: "Багатский район" },
      { nameUz: "Gurlan tumani", nameUzCyrl: "Гурлан тумани", nameRu: "Гурленский район" },
      { nameUz: "Hazorasp tumani", nameUzCyrl: "Ҳазорасп тумани", nameRu: "Хазараспский район" },
      { nameUz: "Xiva tumani", nameUzCyrl: "Хива тумани", nameRu: "Хивинский район" },
      { nameUz: "Xonqa tumani", nameUzCyrl: "Хонқа тумани", nameRu: "Ханкинский район" },
      { nameUz: "Qo'shko'pir tumani", nameUzCyrl: "Қўшкўпир тумани", nameRu: "Кошкупырский район" },
      { nameUz: "Shovot tumani", nameUzCyrl: "Шовот тумани", nameRu: "Шаватский район" },
      { nameUz: "Urganch tumani", nameUzCyrl: "Урганч тумани", nameRu: "Ургенчский район" },
      { nameUz: "Yangiariq tumani", nameUzCyrl: "Янгиариқ тумани", nameRu: "Янгиарыкский район" },
      { nameUz: "Yangibozor tumani", nameUzCyrl: "Янгибозор тумани", nameRu: "Янгибазарский район" },
    ],
  },
];
