name: Deploy ProHome B2C Backend to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          timeout: 60s
          command_timeout: 30m
          envs: GH_TOKEN
          script: |
            set -e
            echo "📁 Creating app folder..."
            mkdir -p /var/www/prohome/b2c/backend
            cd /var/www/prohome/b2c/backend

            if [ ! -d ".git" ]; then
              echo "📥 Cloning private repository..."
              # Bu yerda secrets.GH_TOKEN emas, shunchaki $GH_TOKEN (envs dan keladi)
              git clone https://x-access-token:${GH_TOKEN}@github.com/DaminboevMuhammadrizo/Prohome-Backend-B2C .
            else
              echo "♻️ Pulling latest code..."
              git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/DaminboevMuhammadrizo/Prohome-Backend-B2C
              git reset --hard
              git pull origin main
            fi

            echo "🛑 Managing containers..."
            docker compose down --remove-orphans || true

            echo "🛠️ Building and Starting..."
            docker compose build --no-cache
            docker compose up -d

            echo "🧹 Cleaning up..."
            docker builder prune -f
            docker image prune -f

            echo "🎉 ProHome Deploy finished successfully!"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
